//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activ
    {
        public int ID { get; set; }
        public string NameActiv { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Juri { get; set; }
        public string Win { get; set; }
    }
}
