//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public string Name_RU { get; set; }
        public string Name_EN { get; set; }
        public string Cod_RU { get; set; }
        public string Cod_EN { get; set; }
    }
}
